@Backend_HostAddress = http://localhost:5206

GET {{Backend_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{Backend_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "Password@123"
}

###

POST {{Backend_HostAddress}}/api/auth/refresh
Content-Type: application/json

{
  "refreshToken": "paste-the-refresh-token-from-login-here"
}
